################################################################################
# Automatically-generated file. Do not edit!
################################################################################

OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
EXECUTABLES := 
OBJS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
apps/about \
apps/antelope \
apps/at-master \
apps/calc \
apps/cmdd \
apps/codeprop \
apps/collect-view \
apps/dhcp \
apps/directory \
apps/email \
apps/er-coap \
apps/ftp \
apps/http-post-auth \
apps/httpd-ws \
apps/ipso-objects \
apps/irc \
apps/json \
apps/mqtt \
apps/netconf \
apps/oma-lwm2m \
apps/orchestra \
apps/ping6 \
apps/powertrace \
apps/process-list \
apps/program-handler \
apps/rest-engine \
apps/serial-shell \
apps/servreg-hack \
apps/shell \
apps/slip-cmd \
apps/telnet \
apps/telnetd \
apps/unit-test \
apps/webbrowser \
apps/webserver \
apps/webserver-nano \
core/cfs \
core/ctk \
core/ctk/libconio \
core/dev \
core/lib \
core/lib/strncasecmp \
core/loader \
core/net/http-socket \
core/net/ip \
core/net/ip64 \
core/net/ipv4 \
core/net/ipv6/multicast \
core/net/ipv6 \
core/net \
core/net/llsec \
core/net/llsec/noncoresec \
core/net/mac/contikimac \
core/net/mac \
core/net/mac/cxmac \
core/net/mac/sicslowmac \
core/net/mac/tsch \
core/net/rime \
core/net/rpl \
core/sys \
cpu/6502/ctk \
cpu/6502/ethconfig \
cpu/6502/ipconfig \
cpu/6502/lib \
cpu/6502/net \
cpu/6502/serconfig \
cpu/6502/sys \
cpu/arm/aducrf101/Common/GCC \
cpu/arm/aducrf101/Common/IAR \
cpu/arm/aducrf101/Common/RealView \
cpu/arm/aducrf101/Common \
cpu/arm/aducrf101 \
cpu/arm/aducrf101/dev \
cpu/arm/at91sam7s \
cpu/arm/at91sam7s/loader \
cpu/arm/common/SD-card \
cpu/arm/common/dbg-io \
cpu/arm/common/sys \
cpu/arm/common/usb/cdc-acm \
cpu/arm/common/usb/cdc-eth \
cpu/arm/common/usb/msc \
cpu/arm/common/usb \
cpu/arm/stm32f103 \
cpu/arm/stm32l152 \
cpu/avr \
cpu/avr/dev \
cpu/avr/dev/usb/rndis \
cpu/avr/dev/usb/serial \
cpu/avr/dev/usb/storage \
cpu/avr/dev/usb \
cpu/avr/radio/ieee-manager \
cpu/avr/radio/mac \
cpu/avr/radio/rf230 \
cpu/avr/radio/rf230bb \
cpu/cc2538 \
cpu/cc2538/dev \
cpu/cc2538/usb \
cpu/cc253x/dev \
cpu/cc253x \
cpu/cc253x/usb \
cpu/cc253x/usb/common/cdc-acm \
cpu/cc253x/usb/common \
cpu/cc26xx-cc13xx \
cpu/cc26xx-cc13xx/dev \
cpu/cc26xx-cc13xx/rf-core \
cpu/mc1322x \
cpu/mc1322x/lib \
cpu/mc1322x/src \
cpu/mc1322x/tests \
cpu/mc1322x/tools/ftditools \
cpu/mc1322x/tools \
cpu/msp430 \
cpu/msp430/dev \
cpu/msp430/f1xxx \
cpu/msp430/f2xxx \
cpu/msp430/f5xxx \
cpu/native/dev \
cpu/native \
cpu/native/net \
cpu/nrf52832/ble \
cpu/nrf52832/dev \
cpu/nrf52832 \
cpu/pic32 \
cpu/pic32/lib \
cpu/rl78 \
cpu/rl78/adf7023 \
cpu/rl78/sys \
cpu/stm32f105 \
cpu/stm32f105/lib/CMSIS/CM3/CoreSupport \
cpu/stm32f105/lib/CMSIS/CM3/DeviceSupport/ST/STM32F10x/startup \
cpu/stm32f105/lib/CMSIS/CM3/DeviceSupport/ST/STM32F10x \
cpu/stm32f105/lib/STM32F10x_StdPeriph_Driver/src \
cpu/stm32f105/lib/STM32_USB_Device_Library/Class/audio/src \
cpu/stm32f105/lib/STM32_USB_Device_Library/Class/cdc/src \
cpu/stm32f105/lib/STM32_USB_Device_Library/Class/customhid/src \
cpu/stm32f105/lib/STM32_USB_Device_Library/Class/dfu/src \
cpu/stm32f105/lib/STM32_USB_Device_Library/Class/hid/src \
cpu/stm32f105/lib/STM32_USB_Device_Library/Class/hid_cdc_wrapper/src \
cpu/stm32f105/lib/STM32_USB_Device_Library/Class/hid_msc_wrapper/src \
cpu/stm32f105/lib/STM32_USB_Device_Library/Class/msc/src \
cpu/stm32f105/lib/STM32_USB_Device_Library/Core/src \
cpu/stm32f105/lib/STM32_USB_OTG_Driver/src \
cpu/stm32f105/usb \
cpu/stm32w108 \
cpu/stm32w108/dev \
cpu/stm32w108/e_stdio/src \
cpu/stm32w108/hal/micro/cortexm3 \
cpu/stm32w108/hal/micro/cortexm3/stm32w108 \
cpu/stm32w108/small-printf \
cpu/x86 \
cpu/x86/drivers/legacy_pc \
cpu/x86/drivers/quarkX1000 \
cpu/x86/init/common \
cpu/x86/init/legacy_pc \
cpu/x86/mm \
cpu/x86/uefi \
dev/bme280 \
dev/cc1200 \
dev/cc2420 \
dev/cc2520 \
dev/disk/mmc \
dev/ds2411 \
dev/dw1000/decadriver \
dev/dw1000 \
dev/dw1000/tdoa/decadriver_api \
dev/dw1000/tdoa/tdoa_anchor \
dev/dw1000/tdoa \
dev/dw1000/tdoa/tdoa_tag \
dev/dw1000/tdoa/tdoa_tag/position_estimator \
dev/enc28j60 \
dev/pms5003 \
dev/sht11 \
doc \
examples/antelope/netdb \
examples/antelope/shell \
examples/avr-rss2/AES128HW_test \
examples/avr-rss2/avr_radio_power \
examples/avr-rss2/hello-sensors \
examples/avr-rss2/ipv6/dc-rpl-coap \
examples/avr-rss2/ipv6/dc-rpl-coap/dev \
examples/avr-rss2/ipv6/dc-rpl-coap/resources \
examples/avr-rss2/ipv6/rpl-border-router \
examples/avr-rss2/ipv6/rpl-udp-report \
examples/avr-rss2/ipv6/sensd_client \
examples/cc2530dk \
examples/cc2530dk/border-router \
examples/cc2530dk/cc2531-usb-demo \
examples/cc2530dk/udp-ipv6 \
examples/cc2538-common/crypto \
examples/cc2538-common/mqtt-demo \
examples/cc2538-common/pka \
examples/cc2538-common \
examples/cc2538dk \
examples/cc2538dk/udp-ipv6-echo-server \
examples/cc26xx \
examples/cc26xx/cc26xx-web-demo \
examples/cc26xx/cc26xx-web-demo/resources \
examples/cc26xx/very-sleepy-demo \
examples/cfs-coffee \
examples/collect \
examples/econotag-ecc-test \
examples/econotag-flash-test \
examples/eeprom-test \
examples/email \
examples/er-rest-example \
examples/er-rest-example/resources \
examples/example-shell \
examples/extended-rf-api \
examples/fat \
examples/ftp \
examples/galileo \
examples/hello-world \
examples/http-socket \
examples/ip64-router \
examples/ipso-objects \
examples/ipv6/json-ws \
examples/ipv6/multicast \
examples/ipv6/native-border-router \
examples/ipv6/rpl-border-router \
examples/ipv6/rpl-collect \
examples/ipv6/rpl-tsch \
examples/ipv6/rpl-udp \
examples/ipv6/simple-udp-rpl \
examples/ipv6/sky-websense \
examples/ipv6/slip-radio \
examples/irc \
examples/irc-80col \
examples/jn516x/dr1175-sensors \
examples/jn516x/rime \
examples/jn516x/rpl/border-router \
examples/jn516x/rpl/coap-dongle-node \
examples/jn516x/rpl/coap-dr1175-node \
examples/jn516x/rpl/coap-dr1199-node \
examples/jn516x/rpl/node \
examples/jn516x/rpl/tools \
examples/jn516x/tsch/simple-sensor-network/node \
examples/jn516x/tsch/simple-sensor-network/rpl-border-router \
examples/jn516x/tsch/tools \
examples/jn516x/tsch/tx-power-verification/node \
examples/jn516x/tsch/tx-power-verification/rpl-border-router \
examples/jn516x/tsch/uart1-test-node \
examples/llsec/ccm-star-tests/encryption \
examples/llsec/ccm-star-tests/verification \
examples/mbxxx/acc-sensor \
examples/mbxxx/button \
examples/mbxxx/coffee-test \
examples/mbxxx/mbxxx-shell \
examples/mbxxx/mbxxx-websense \
examples/mbxxx/shell-exec \
examples/mbxxx/telnet-server \
examples/mbxxx/temperature \
examples/mbxxx/udp-ipv6-sleep \
examples/mbxxx/webserver-ajax \
examples/multi-threading \
examples/netperf \
examples/nrf52dk/blink-hello \
examples/nrf52dk/coap-demo \
examples/nrf52dk/coap-demo/resources \
examples/nrf52dk/mqtt-demo \
examples/nrf52dk/timer-test \
examples/openmote-cc2538 \
examples/ping-ipv6 \
examples/powertrace \
examples/ravenusbstick \
examples/rf_environment \
examples/rime \
examples/rime-tsch \
examples/rssi-scanner \
examples/seedeye/powerswitch \
examples/sensniff \
examples/servreg-hack \
examples/settings-example \
examples/sky \
examples/sky-ip \
examples/sky-shell \
examples/sky-shell-exec \
examples/sky-shell-webserver \
examples/stm32nucleo-spirit1/sensor-demo \
examples/tcp-socket \
examples/tdoa3_ranging/obj_evb1000 \
examples/tdoa3_ranging \
examples/tdoa_tag_positioning/obj_evb1000 \
examples/tdoa_tag_positioning \
examples/telnet-server \
examples/timers \
examples/trickle-library \
examples/udp-ipv6 \
examples/udp-stream \
examples/webbrowser \
examples/webbrowser-80col \
examples/webserver \
examples/webserver-ipv6 \
examples/webserver-ipv6-raven \
examples/websockets \
examples/wget \
examples/zolertia/z1/ipv6/z1-websense \
examples/zolertia/z1 \
examples/zolertia/zoul/at-test \
examples/zolertia/zoul/cc1200-demo \
examples/zolertia/zoul/orion/client \
examples/zolertia/zoul/orion/ip64-router \
examples/zolertia/zoul/rev-a \
examples/zolertia/zoul/rev-b \
examples/zolertia/zoul/rtcc \
examples/zolertia/zoul \
lib/fs/fat \
lib/fs/fat/option \
lib/fs/fat/option/unicode \
lib/newlib \
platform/apple2enh \
platform/apple2enh/lib \
platform/apple2enh/sys \
platform/atarixl \
platform/atarixl/lib \
platform/avr-atmega128rfa1/apps/raven-ipso \
platform/avr-atmega128rfa1/apps/raven-lcd-interface \
platform/avr-atmega128rfa1/apps/raven-webserver \
platform/avr-atmega128rfa1 \
platform/avr-raven/apps/raven-ipso \
platform/avr-raven/apps/raven-lcd-interface \
platform/avr-raven/apps/raven-webserver \
platform/avr-raven \
platform/avr-ravenlcd \
platform/avr-ravenusb \
platform/avr-rcb \
platform/avr-rss2 \
platform/avr-rss2/dev \
platform/avr-zigbit \
platform/c128 \
platform/c128/lib \
platform/c64 \
platform/c64/lib \
platform/cc2530dk \
platform/cc2530dk/dev \
platform/cc2538dk \
platform/cc2538dk/dev \
platform/cooja/cfs \
platform/cooja \
platform/cooja/dev \
platform/cooja/lib \
platform/cooja/net \
platform/cooja/sys \
platform/cooja/testapps \
platform/cooja-ip64 \
platform/econotag/apps/ecc \
platform/econotag/apps/flash \
platform/econotag \
platform/ev-aducrf101mkxz \
platform/eval-adf7xxxmb4z \
platform/evb1000 \
platform/evb1000/dev \
platform/evb1000/evb-newlib \
platform/exp5438 \
platform/galileo \
platform/galileo/core/sys \
platform/galileo/drivers \
platform/galileo/net \
platform/jn516x \
platform/jn516x/dev \
platform/jn516x/dev/dongle \
platform/jn516x/dev/dr1174 \
platform/jn516x/dev/dr1175 \
platform/jn516x/dev/dr1199 \
platform/jn516x/lib \
platform/mbxxx/apps \
platform/mbxxx \
platform/mbxxx/dev \
platform/micaz/apps \
platform/micaz/apps/mts310 \
platform/micaz \
platform/micaz/dev \
platform/micaz/dev/sensors \
platform/minimal-net \
platform/native \
platform/native/ctk \
platform/native/dev \
platform/nrf52dk \
platform/nrf52dk/dbg-io \
platform/nrf52dk/dev \
platform/nrf52dk/rtt \
platform/openmote-cc2538 \
platform/openmote-cc2538/dev \
platform/seedeye \
platform/seedeye/dev \
platform/seedeye/dev/mrf24j40 \
platform/sky/apps \
platform/sky \
platform/sky/dev \
platform/srf06-cc26xx/common \
platform/srf06-cc26xx \
platform/srf06-cc26xx/launchpad \
platform/srf06-cc26xx/launchpad/cc1350 \
platform/srf06-cc26xx/sensortag \
platform/srf06-cc26xx/sensortag/cc1350 \
platform/srf06-cc26xx/sensortag/cc2650 \
platform/srf06-cc26xx/srf06 \
platform/stm32nucleo-spirit1 \
platform/stm32nucleo-spirit1/dev \
platform/stm32test \
platform/win32/cfs \
platform/win32 \
platform/win32/ctk \
platform/win32/loader \
platform/wismote/apps \
platform/wismote \
platform/wismote/dev \
platform/z1/apps \
platform/z1 \
platform/z1/dev \
platform/zoul \
platform/zoul/dev \
platform/zoul/firefly \
platform/zoul/firefly-reva \
platform/zoul/fs/fat \
platform/zoul/orion \
platform/zoul/remote-reva \
platform/zoul/remote-revb \
regression-tests/03-base/code \
regression-tests/04-rime/code \
regression-tests/11-ipv6/code/receiver \
regression-tests/11-ipv6/code/sender \
regression-tests/12-rpl/code \
regression-tests/17-slip-radio/code \
regression-tests/21-large-rpl/code/node \
regression-tests/21-large-rpl/code/router \
regression-tests/23-rpl-non-storing/code \
regression-tests/25-ieee802154/code \
regression-tests/27-tsch/code \
tools/blaster \
tools \
tools/cooja/config \
tools/cooja/examples/project_new_interface \
tools/jn516x \
tools/release-tools/compile-platforms \
tools/sky \
tools/sky/uip6-bridge/dev \
tools/sky/uip6-bridge \
tools/stm32w \
tools/stm32w/uip6_bridge/dev \
tools/stm32w/uip6_bridge \
tools/stm32w/wpcapslip6 \
tools/wpcapslip \
tools/z80/hex2bin/src \

